# Generated by Django 3.0.5 on 2021-02-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_dimensions', '0002_auto_20210123_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
